create table LESSON(
  LESSON_ID int PRIMARY KEY NOT NULL
    GENERATED ALWAYS AS IDENTITY(START WITH 1,INCREMENT BY 1),
    LESSONNAME VARCHAR(100),
    COURSECOM VARCHAR(255),
    URL VARCHAR(255)
          );